### ISSUE TITLE
Query Regarding Hosting Service

### ISSUE THREAD

**Issue by OtherGitAcc** [qqap/trulyquantumchess#1]
Thanks a lot for making the game available online again! Could you please let me know whether you are using a popular service to host the game? We wanted to host a small tournament and hence could not use the new link you have provided, as the new build has Stockfish's access.

**Comment by qqap** [comment]
Hi

I've added a query parameter `&suggestions=false` that you can append to the end of the URL to disable suggestions. Unfortunately, I'm not using any hyperscalers for hosting this project at the moment.

Feel free to star the project if you like it. Thank you!! :)
